// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8MQ8pTC1bqP_L_yVvvQdtJm-vG6Ugp_8',
    appId: '1:10476604159:web:fd31c13e783656c4779aca',
    messagingSenderId: '10476604159',
    projectId: 'smarttrack-b6d89',
    authDomain: 'smarttrack-b6d89.firebaseapp.com',
    storageBucket: 'smarttrack-b6d89.firebasestorage.app',
    measurementId: 'G-0R96LRE5TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ywVYfiyYIs1cB8qcLaogwEIEUkD10dY',
    appId: '1:10476604159:android:4e69f761979448e2779aca',
    messagingSenderId: '10476604159',
    projectId: 'smarttrack-b6d89',
    storageBucket: 'smarttrack-b6d89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQY8Q0Qr4xHlOp44yoYdZ4nSurBHiKbc',
    appId: '1:10476604159:ios:0ab7053eb28b1f2c779aca',
    messagingSenderId: '10476604159',
    projectId: 'smarttrack-b6d89',
    storageBucket: 'smarttrack-b6d89.firebasestorage.app',
    iosBundleId: 'com.example.newTst',
  );

}